// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxzGUnAc3NNp94s6NAhXdHbsoG_Q2pnk',
    appId: '1:1000506502502:web:cf6b7fc276f73321722ca7',
    messagingSenderId: '1000506502502',
    projectId: 'flutter-ncsnxthck-sust-ghle',
    authDomain: 'flutter-ncsnxthck-sust-ghle.firebaseapp.com',
    storageBucket: 'flutter-ncsnxthck-sust-ghle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJAiL3EOVkP8ejKSEblnV0HMvuh2Cfg0',
    appId: '1:1000506502502:android:9f01ac5528925936722ca7',
    messagingSenderId: '1000506502502',
    projectId: 'flutter-ncsnxthck-sust-ghle',
    storageBucket: 'flutter-ncsnxthck-sust-ghle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOiipiKBkMwtQRWEKkv6rp-mN4d1KlodI',
    appId: '1:1000506502502:ios:8fc7e7d0a80d1d07722ca7',
    messagingSenderId: '1000506502502',
    projectId: 'flutter-ncsnxthck-sust-ghle',
    storageBucket: 'flutter-ncsnxthck-sust-ghle.appspot.com',
    iosClientId: '1000506502502-je2gu2vtn8d09mtl6gtkos08hrj7k3el.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNcsnxthckSustGhle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOiipiKBkMwtQRWEKkv6rp-mN4d1KlodI',
    appId: '1:1000506502502:ios:8fc7e7d0a80d1d07722ca7',
    messagingSenderId: '1000506502502',
    projectId: 'flutter-ncsnxthck-sust-ghle',
    storageBucket: 'flutter-ncsnxthck-sust-ghle.appspot.com',
    iosClientId: '1000506502502-je2gu2vtn8d09mtl6gtkos08hrj7k3el.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNcsnxthckSustGhle',
  );
}
